[tool.poetry]
name = "kscmyeah"
version = "0.1.0"
description = ""
authors = ["js <jazzinimal@googlemail.com>"]

[tool.poetry.dependencies]
python = "^3.7.7"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
