default_context:
  project_name: 'Base Project'
  project_slug: 'KSCm'
  domain_main: 'KSCm.com'
  domain_staging: 'stag.KSCm.com'
  docker_swarm_stack_name_main: 'KSCm-com'
  docker_swarm_stack_name_staging: 'stag-KSCm-com'
  secret_key: 'fa46d17b8d7d26b5e628305b5b54a4eca52f5ba004e8eba0845fbf5391f16728'
  first_superuser: 'janosch@ideentwickler.com'
  first_superuser_password: 'Zutritt$$22'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.KSCm.com", "https://stag.KSCm.com", "https://KSCm.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@KSCm.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'janosch@ideentwickler.com'
  pgadmin_default_user_password: 'Zutritt$$22'
  traefik_constraint_tag: 'KSCm.com'
  traefik_constraint_tag_staging: 'stag.KSCm.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Zutritt$$22'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
