"""fixed support enum on store model

Revision ID: 17577b966ca2
Revises: ebe0c31d37f0
Create Date: 2021-02-09 14:13:46.948334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17577b966ca2'
down_revision = 'ebe0c31d37f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
