"""manuell adding enum claimkind

Revision ID: 539a37695e89
Revises: d69ad981b5fa
Create Date: 2021-02-10 19:07:43.739674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539a37695e89'
down_revision = 'd69ad981b5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # https://stackoverflow.com/questions/14845203/altering-an-enum-field-using-alembic
    op.execute("COMMIT")
    op.execute("ALTER TYPE claimkind ADD VALUE 'CUSTOMER'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
