"""removed lazy, trying uselist

Revision ID: 6acc888e1a5f
Revises: e5c320ac0349
Create Date: 2021-02-10 09:41:50.569617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acc888e1a5f'
down_revision = 'e5c320ac0349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
