"""added CUSTOMER KIND TO CLAIMKIND

Revision ID: a886dfd53359
Revises: f249ecc40691
Create Date: 2021-02-10 18:20:06.227663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a886dfd53359'
down_revision = 'f249ecc40691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
