"""added model claim

Revision ID: bbbbe2764f75
Revises: ea0bd90a155c
Create Date: 2021-02-10 12:38:01.942309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbbe2764f75'
down_revision = 'ea0bd90a155c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill', sa.Float(), nullable=False),
    sa.Column('discharge', sa.Float(), nullable=True),
    sa.Column('kind', sa.Enum('WAREHOUSE', 'SUPPLIER', 'ASSEMBLER', 'SELLER', name='claimkind'), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('store_internal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['store_internal_id'], ['store.internal_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_id'), 'claim', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_id'), table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
