"""added CUSTOMER KIND TO CLAIMKIND

Revision ID: d69ad981b5fa
Revises: a886dfd53359
Create Date: 2021-02-10 18:33:54.309768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69ad981b5fa'
down_revision = 'a886dfd53359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
