"""changed all relationships to lazy: dynamic mode

Revision ID: e5c320ac0349
Revises: 72c1063afebe
Create Date: 2021-02-10 09:32:13.736961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c320ac0349'
down_revision = '72c1063afebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
