"""ticket model, changed to store backref ticket_set

Revision ID: ea0bd90a155c
Revises: 6acc888e1a5f
Create Date: 2021-02-10 09:45:06.581411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0bd90a155c'
down_revision = '6acc888e1a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
