"""added contract_nr to claim model

Revision ID: f249ecc40691
Revises: bbbbe2764f75
Create Date: 2021-02-10 12:48:17.924991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f249ecc40691'
down_revision = 'bbbbe2764f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('contract_nr', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_claim_contract_nr'), 'claim', ['contract_nr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_contract_nr'), table_name='claim')
    op.drop_column('claim', 'contract_nr')
    # ### end Alembic commands ###
